---
title: "Publications"
---


###     William Meiniel, Piernicola Spinicelli, Elsa D. Angelini, Alexandra Fragola, Vincent Loriette, François Orieux, Eduardo Sepulveda, and Jean-Christophe Olivo-Marin. "Reducing data acquisition for fast structured illumination microscopy using compressed sensing." ISBI 2017

###     Pierre Vermeulen, H Zhan, François Orieux, Olivo-Marin Jean-Christophe, Zsolt Lenkei, Vincent Loriette, Alexandra Fragola. "Out of focus background subtraction for fast structured illumination super resolution microscopy of optically thick samples."     Journal of Microscopy, Wiley, 2015, 259 (3), pp.257-268 <10.1111/jmi.12259>.
 <a href="http://dx.doi.org/10.1111/jmi.12259" aria-hidden="true"></i></a>

###     François Orieux, Eduardo Sepulveda, Vincent Loriette, Benoit Dubertret, Jean-Christophe Olivo-Marin. "Bayesian Estimation for Optimized Structured Illumination Microscopy."     IEEE Transactions on Image Processing, Institute of Electrical and Electronics Engineers, 2012, <10.1109/TIP.2011.2162741>.
 <a href="http://dx.doi.org/10.1109/TIP.2011.2162741" aria-hidden="true"></i></a>
